### ISSUE TITLE
/server + Tab

### ISSUE THREAD

**Issue by Oxro** [SpigotMC/BungeeCord#2235] opened 2017-08-30 15:14 UTC
Pressing tab after typing /server disconnects the user with the error - https://pastebin.com/raw/Jzxf7kmc

**Comment by Black-Hole** [comment] 2017-08-30 19:24
Duplicate of https://github.com/SpigotMC/BungeeCord/issues/2233

**Closed** 2017-08-30 21:38 UTC
