### ISSUE TITLE
BungeeCord Shows player online but actually not there

### ISSUE THREAD

**Issue by JHXSMatthew** [SpigotMC/BungeeCord#1734] opened 2016-02-06 06:07 UTC
Hi,
Recently several players say they are not online but they got "You are already connected to the server" when joining.
Here is some pictures for player having this issue named "Veneno_Craft1":

BungeeCord indicates he is on "kb3" server , but he is not in playerlist of "kb3".

Image:
http://postimg.org/image/k3sxqh509/

And then, I try to check my configs, nothing wrong:

Image:
http://postimg.org/image/wmu7f0xvb/

I believe there is a bug or something wrong.

Use latest build, Build 1115 (http://ci.md-5.net/job/BungeeCord/1115/)

 Thanks for your time :)

**Comment by md-5** [comment] 2016-02-06 06:08
After how long? Players may take up to 30 seconds to time out on a poorly configured network.

**Comment by JHXSMatthew** [comment] 2016-02-06 06:10
More thank 24 hours.
I tried to use ProxiedPlayer.disconnect method to disconnect him, not working, he is still can be found.

**Comment by Black-Hole** [comment] 2016-02-06 09:51
Should already be fixed by recent BungeeCord versions. Commit: https://github.com/SpigotMC/BungeeCord/commit/e556fd7150d5b0711cacdda3a77842cb12fdd963

**Comment by Janmm14** [comment] 2016-02-06 10:13
@Black-Hole he uses the latest bungeecord version already.

**Comment by NickG365** [comment] 2016-02-07 17:51
Are you using any BungeeCord plugins?  What OS are you running BungeeCord on?

**Comment by JHXSMatthew** [comment] 2016-02-08 08:09
@NickG365 
Yes, I do use plugins.
List:
**advanced-bungee-announcer-0.2 by Tux
BungeeControl By me, simple party system and lobby balancer . 
SkinsRestorer-v10.5.1 By Troller
**

CentOS 6.5 , with 64GB RAM,Bungee takes 56GB
. Currently ~5000 people online.

**Comment by md-5** [comment] 2016-02-08 09:01
Please don't allocate so much ram to bungee. You would probably be better
off with a quarter of that.

**Comment by JHXSMatthew** [comment] 2016-02-08 09:13
@md-5
Is 32GB good for 5000 people ?
mmm, K, I would try only 32GB.

**Comment by md-5** [comment] 2016-02-08 09:30
Honestly 16gb should be plenty.

**Comment by JHXSMatthew** [comment] 2016-02-08 09:33
16GB for 5000 people ?
No, I tried 24GB, feel lag after 48 hours.

**Comment by minecrafter** [comment] 2016-02-08 23:06
You feel the lag because Java needs to perform garbage collection over all that 24GB of RAM. I would recommend allocating at maximum 8GB of memory.

**Comment by JHXSMatthew** [comment] 2016-02-09 06:12
@minecrafter
Then G1 GC would try to allocate more up to 12GB , lag starts.
I was using 4GB while 400 people , fell lag when it reaches to ~800,
Then I increase to 8GB, fell lag when it reaches ~1500.
And what's worse, I even suffered from STW gc.
But I will give it a try with 8GB heap allocation for a few days to see what's going on.
Thanks !

**Comment by Xayanix** [comment] 2016-02-13 16:39
I can confirm this bug.
Im running network with about 1000 players online, some of them are not disconnecting and staying online to next proxy restart. I have allocated 4G.

**Comment by NickG365** [comment] 2016-02-13 18:34
@Xayanix Are you running any BungeeCord plugins?  What version are you running?

**Comment by Xayanix** [comment] 2016-02-13 22:05
I'm using only my own plugin and always newest BungeeCord.
My friends have same issue.

**Comment by NickG365** [comment] 2016-02-13 23:00
Can you provide the source for the custom plugin?  I'm led to believe that a leak in the plugin would be the cause of the issue, considering there aren't widespread reports of this happening.

**Comment by JHXSMatthew** [comment] 2016-02-14 09:30
@NickG365 
Hi, after a few days running BungeeCord instance.
I am still having this kind of issue.

If it is causing by @Xayanix 's plugin, I should not have this issue.

Cheers.

**Comment by Xayanix** [comment] 2016-02-14 10:40
I can't post source of my whole plugin. Anyways it is not causing issue...
I told you that my friend has same issue.

**Comment by Paulomart** [comment] 2016-02-14 10:47
I'm able to reproduce this on my instance too, with ~200 bots online. When I interrupt my bot app, aka giving a timeout, some bots say online. Using the fuckoff plugin (google for it) fixes the problem.

**Comment by Janmm14** [comment] 2016-02-14 12:56
Maybe this issue is also related to the delayed disconnect, but that needs to be tested.

**Comment by md-5** [comment] 2016-02-22 00:00
https://github.com/SpigotMC/BungeeCord/commit/0646a3090a2f1b5246ea3f7e1d69218e92018af5

**Closed by md-5** 2016-02-22 00:00 UTC

**Comment by JHXSMatthew** [comment] 2016-02-28 06:46
Still having this issue while I updating to latest
