### ISSUE TITLE
Bug disconnected

### ISSUE THREAD

**Issue by ali120** [SpigotMC/BungeeCord#2238] opened 2017-09-01 07:16 UTC
07:15:46 [INFO] [Pan7erfaustin] <-> ServerConnector [lobby] has connected
07:15:54 [INFO] [Pan7erfaustin] <-> ServerConnector [ffa] has connected
07:15:54 [SEVERE] [Pan7erfaustin] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: FCEncoder must produce at least one message.
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036)
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
    at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:149)
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:236)
    at net.md_5.bungee.protocol.packet.Login.handle(Login.java:72)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)
07:15:54 [INFO] [Pan7erfaustin] disconnected with: EncoderException : FCEncoder must produce at least one message. @ io.netty.handler.codec.MessageToMessageEncoder:98
07:15:54 [INFO] [Pan7erfaustin] -> UpstreamBridge has disconnected
07:15:54 [INFO] [Pan7erfaustin] <-> DownstreamBridge <-> [lobby] has disconnected
07:15:54 [INFO] [Pan7erfaustin] <-> DownstreamBridge <-> [ffa] has disconnected

help me plzzzzzz

**Comment by TheMolkaPL** [comment] 2017-09-01 07:31
__FCEncoder is not from BungeeCord__ - please remove all your plugins and test it again.

**Comment by Black-Hole** [comment] 2017-09-01 11:25
Duplicate of #2188

**Closed** 2017-09-01 11:28 UTC
