### ISSUE TITLE
Player login Two times

### ISSUE THREAD

**Issue by Sprungente** [SpigotMC/BungeeCord#2229] opened 2017-08-19 17:08 UTC
Hello everybody

I think it is an issue. It makes many new player fusterated. I have asked into the spigotmc.org forums https://www.spigotmc.org/threads/player-login-two-times.266355/ to get a solution.

So i have to ask here.  

I use the newest Build and it's happening on Players, they have never been on the servernetwork and have the wrong minecraftversion.

No error it will happen but this: 
18:27:34 [INFORMATION] [BungeePerms] Login by RuskyException (9969dbdc-d54f-4280-a707-24a95a438b52)
18:27:34 [INFORMATION] [RuskyException] <-> ServerConnector [Lobby] has connected
18:27:34 [INFORMATION] [RuskyException] <-> ServerConnector [Citybuild] has connected
18:27:34 [INFORMATION] [RuskyException] <-> ServerConnector [Lobby] has disconnected
18:27:35 [INFORMATION] [RuskyException] <-> ServerConnector [Citybuild] has disconnected
18:27:36 [INFORMATION] [RuskyException] -> UpstreamBridge has disconnected

It will be very nice when it's possible to fix this issue

**Comment by Black-Hole** [comment] 2017-08-19 19:44
The player is connected to the Lobby server, the connection fails then he's connected to the Citybuild server. That connection fails too. BungeeCord just has to wait for the Spigot server to close the connection.

Every time a player switches servers, the connection the new server is established and then the connection to the old server is closed.

What is your issue?

**Comment by i9hdkill** [comment] 2017-08-19 20:01
Try to reproduce without Protocolplugins like ViaVersion or Protocolsupport. Seems like a feature - not a bug.
Closing for now. If you still get these issues without plugins, provide more info. Otherwise we can't help you.

**Closed by i9hdkill** 2017-08-19 20:01 UTC

**Comment by Sprungente** [comment] 2017-08-19 21:56
hey people thanks you for answering

@Black-Hole i know what you meen but why it is happen only for player they was never been on the server?

@i9hdkill i don't need protocolplugins like this what you say
I use
Bungeeadmintools: https://www.spigotmc.org/resources/bungee-admin-tools-basics-edition.444/
Bungeealiases https://www.spigotmc.org/resources/bungeealiases.4107/
Bungeechat https://www.spigotmc.org/resources/bungee-chat.12592/
Bungeeonlinetime https://www.spigotmc.org/resources/bungeeonlinetime.795/
Bungeeperms https://www.spigotmc.org/resources/bungeeperms.25/
Bungetablistplus https://www.spigotmc.org/resources/bungeetablistplus.313/
Party & friends + PAF Clans https://www.spigotmc.org/resources/party-and-friends-extended-edition-for-bungeecord-supports-1-7-1-12-1.10123/  :::::: https://www.spigotmc.org/resources/clans-for-party-and-friends-extended-for-bungeecord.13890/
Livesupportchat: https://www.spigotmc.org/resources/livesupportchatbungee.43020/

Maybe you find a reason for my issue
