### ISSUE TITLE
Kicking players with error

### ISSUE THREAD

**Issue by SpearDevelopment1** [SpigotMC/BungeeCord#3523] opened 2023-09-23 21:27 UTC
### Bungeecord version

BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:f486a25:173

### Server version

Paper version git-Paper-1620 (MC: 1.12.2)

### Client version

1.12.2

### Bungeecord plugins

pxBungee

### The bug

Hello, 

My server Kicking players from one server on the network.
it kicked me and i got the error below in console.

### Log output (links)

```
INFO] [Buzzflow69] <-> ServerConnector [lobby] has connected
21:17:05 [INFO] [Buzzflow69] <-> DownstreamBridge <-> [skyblock] has disconnected
21:17:05 [SEVERE] [Buzzflow69] -> UpstreamBridge - encountered exception
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
    at net.md_5.bungee.netty.ChannelWrapper.getEncodeProtocol(ChannelWrapper.java:51)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:139)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:132)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
21:17:05 [INFO] [Buzzflow69] disconnected with: NullPointerException : Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null @ net.md_5.bungee.netty.ChannelWrapper:51
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment] 2023-09-24 00:07
Continue using your issue #3520 !

**Comment by bob7l** [comment] 2023-09-24 04:56
The only way I've managed to reproduce this error is if the connecting to server (skyblock in your instance) is closed during the ServerConnector stage (After sending StartConfiguration). All the elements in the pipeline are probably being wiped the second the channel is closed, which would explain the error.

The "solution" to the ERROR would be to just check if the server is connected before attempting to get the decode protocol in UpstreamBridge->handle#StartConfiguration

However, this error is NOT the cause of your kick problem (Assuming you don't have plugins screwing with the login sequence). It's just the consequence of the connection being terminated - likely due to an error somewhere that may be getting suppressed by a plugin if you can't find it.

**Comment by md-5** [comment] 2023-09-24 05:43
Is the pipeline wiped immediately on close?

**Comment by bob7l** [comment] 2023-09-24 08:56
> Is the pipeline wiped immediately on close?

No I worded that poorly. I mean terminated, from an uncaught exception for instance. That's the only way I've been able to reproduce this error.

**Comment by md-5** [comment] 2023-09-24 10:11
What exception? I would expect it to never be null, but maybe if the exception is in the connection process there would be an issue; or if netty clears all the pipeline handlers on close which is what I meant by wiping and thought you did

**Comment by sasi2006166** [comment] 2023-09-24 10:52
Please fix this issue, you introduced it (or netty did) with 1.20.2

**Comment by bob7l** [comment] 2023-09-24 12:21
> What exception? I would expect it to never be null, but maybe if the exception is in the connection process there would be an issue; or if netty clears all the pipeline handlers on close which is what I meant by wiping and thought you did

Yeah, it's caused by an exception in the connection process (From my testing). 

While connecting to a server, from - say lobby, if a **plugin** sends an incorrect packet downstream during ServerSwitchEvent, it will cause an exception (Likely packet id), which appears to result in the Server's pipeline getting wiped. That then leads to UpstreamBridge hitting a nullpointer when it attempts to access elements from the server's pipeline (Like the error in this thread). 

Is this the only way to reproduce the error? Not sure, but it's the only way I've managed to. 

With your recent patch, this should be resolved. But I'm guessing the issue opener has a plugin sending invalid/non-api packets downstream or something else plugin related. 

That's why I suggested this error just be avoided altogether.  Just going to cause confusion. Maybe just a warning like what you do if a player disconnects during the ServerConnector process? 

Just a note, I tested closing the server's connection in various stages and couldn't produce the error.

**Comment by BoomEaro** [comment] 2023-09-24 13:04
A similar error occurs whenever a client actively sends some packets, such as player position packets, when trying to connect to another server:
https://pastebin.com/3tkTsinN

I managed to replicate this every time a player falls from some elevation, for example if you teleport the player to a height of 10000 blocks (/tp ~ 10000 ~)
(Nowhere any plugins are used, this is impossible to replicate on 1.20.1)

**Comment by sasi2006166** [comment] 2023-09-24 13:05
> A similar error occurs whenever a client actively sends some packets, such as player position packets, when trying to connect to another server: https://pastebin.com/3tkTsinN
> 
> I managed to replicate this every time a player falls from some elevation, for example if you teleport the player to a height of 10000 blocks (/tp ~ 10000 ~) (Nowhere any plugins are used, this is impossible to replicate on 1.20.1)

This issue isn't present on 1.20.1, it got introduced in 1.20.2

**Comment by SpearDevelopment1** [comment] 2023-09-24 18:32
Here's a screenshot of error when kicked.

![image](https://github.com/SpigotMC/BungeeCord/assets/145710949/47b97d2b-7072-4a41-8183-0a108fe7e724)

**Comment by bob7l** [comment] 2023-09-25 08:40
> Here's a screenshot of error when kicked.
> 
> ![image](https://user-images.githubusercontent.com/145710949/270184618-47b97d2b-7072-4a41-8183-0a108fe7e724.png)

Have you tried with zero plugins? I think one of your plugins is either causing, or hiding an exception.

**Comment by md-5** [comment] 2023-09-25 09:06
> A similar error occurs whenever a client actively sends some packets, such as player position packets, when trying to connect to another server: https://pastebin.com/3tkTsinN
> 
> I managed to replicate this every time a player falls from some elevation, for example if you teleport the player to a height of 10000 blocks (/tp ~ 10000 ~) (Nowhere any plugins are used, this is impossible to replicate on 1.20.1 and below)



> > A similar error occurs whenever a client actively sends some packets, such as player position packets, when trying to connect to another server: https://pastebin.com/3tkTsinN
> > I managed to replicate this every time a player falls from some elevation, for example if you teleport the player to a height of 10000 blocks (/tp ~ 10000 ~) (Nowhere any plugins are used, this is impossible to replicate on 1.20.1)
> 
> This issue isn't present on 1.20.1, it got introduced in 1.20.2

I cannot reproduce this. Are you running an actual 1.20.2 spigot server (NOT ViaVersion?)

**Comment by SpearDevelopment1** [comment] 2023-09-25 10:43
> > A similar error occurs whenever a client actively sends some packets, such as player position packets, when trying to connect to another server: https://pastebin.com/3tkTsinN
> 
> > 
> 
> > I managed to replicate this every time a player falls from some elevation, for example if you teleport the player to a height of 10000 blocks (/tp ~ 10000 ~) (Nowhere any plugins are used, this is impossible to replicate on 1.20.1 and below)
> 
> 
> 
> 
> 
> 
> 
> > > A similar error occurs whenever a client actively sends some packets, such as player position packets, when trying to connect to another server: https://pastebin.com/3tkTsinN
> 
> > > I managed to replicate this every time a player falls from some elevation, for example if you teleport the player to a height of 10000 blocks (/tp ~ 10000 ~) (Nowhere any plugins are used, this is impossible to replicate on 1.20.1)
> 
> > 
> 
> > This issue isn't present on 1.20.1, it got introduced in 1.20.2
> 
> 
> 
> I cannot reproduce this. Are you running an actual 1.20.2 spigot server with no bungee or spigot plugins (NOT ViaVersion?)

I'm running a 1.12.2 spigot server , I've removed plugins that I think are interfering. Still no results.

**Comment by md-5** [comment] 2023-09-25 11:49
> As far I know this issue can happen with 1.20.2 proxy and 1.19 spigot, what's seems making the difference is the client version but not always.

This would be extremely surprising to occur on 1.19 given the error is specifically about the 1.20.2 protocol.

The problem is that there are multiple people with multiple different issues in this ticket, which is what happens when you don't create separate tickets.

>  I managed to reproduce the issue simply kicking myself from the spigot console, doesn't happen with disconnection

Please be clear about what issue. Kicking is obviously completely unrelated to changing servers.

**Comment by sasi2006166** [comment] 2023-09-26 18:31
Issue is still present even on latest #3528 request.

**Comment by andrewkm** [comment] 2023-09-26 19:37
Same issue here with **_Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null_** using latest Bungeecord compiled against https://github.com/SpigotMC/BungeeCord/commit/fed646d18b1f40b065902833dfa4fe4ea048f122.

**Comment by md-5** [comment] 2023-09-26 20:58
> Issue is still present even on latest https://github.com/SpigotMC/BungeeCord/pull/3528 request.

Doing what?

**Comment by sasi2006166** [comment] 2023-09-26 20:59
> > Issue is still present even on latest #3528 request.
> 
> Doing what?

Just kicking the player, nothing more.

**Comment by md-5** [comment] 2023-09-26 21:02
"Just kicking" works for me
![image](https://github.com/SpigotMC/BungeeCord/assets/1007849/a3116df5-cebc-4ea6-8cd1-ef4043ebb25d)

**Comment by sasi2006166** [comment] 2023-09-26 21:05
![image](https://github.com/SpigotMC/BungeeCord/assets/49954132/8014f009-f2ae-4c3a-b499-7919a164427c)


This is what I get when there is any kind of kicking

**Comment by Outfluencer** [comment] 2023-09-27 06:59
Couldn't reproduce, I updated my server network to 1.20.2 and neither player nor I have any issues

**Comment by crumpkatrina** [comment] 2023-09-27 15:43
I’ve been getting the same null error when testing the latest bungee and spigot so have opted to stay on 1.20.1 for now.

**Comment by Outfluencer** [comment] 2023-09-27 17:17
Okay i could reproduce it. In 1.8

Kicking the player from the spigot server results in an nullpointer 


17:17:06 [SEVERE] [FameEvil] -> UpstreamBridge - encountered exception
java.lang.NullPointerException

**Comment by Outfluencer** [comment] 2023-09-27 17:33
this error only accours if the player is forwarded to a different server ( another server with priority is registered and the player is sent to this server )

**Closed** 2023-09-27 20:55 UTC
