### ISSUE TITLE
Client still gliding when switching servers

### ISSUE THREAD

**Issue by Foorack** [SpigotMC/BungeeCord#2321] opened 2018-01-07 09:20 UTC
Referring back to previously made issue reports:
[[2059](https://github.com/SpigotMC/BungeeCord/issues/2059) Changing server while flying with elytra makes you stuck in "flying mode"
[[2182](https://github.com/SpigotMC/BungeeCord/issues/2182)] elytra bug

I apologize for the bad audio in the beginning. This video shows proof that it is definitely reproducible on latest BungeeCord and latest Spigot with latest Minecraft. After a few tries I get it at **1:00**.

[https://www.youtube.com/watch?v=TraswOeSOqg](https://www.youtube.com/watch?v=TraswOeSOqg)

The trick is to holding W+SPACE **BEFORE** you get sent to the other server. It is difficult to time this right (as you can see from my attempts in the video). Other more skilled people on the server can replicate it with a much higher success rate. This is an especially big problem as this is possible to do in the minigame servers as well.

**Comment by md-5** [comment] 2018-01-07 12:06
Yes, BungeeCord is not, but the server is - it sends an update for the player as soon as the player spawns in (I have just verified this on my server).
So there are either two scenarios here:
1) Your server is not properly clearing gliding state when the player joins, potentially as a result of plugins installed.
2) The client is ignoring changes to its gliding state

If it is 2), then I'm not sure what BungeeCord can do about it

Please reproduce this issue on a Vanilla server, or failing that a clean install of Spigot.

**Comment by Fejm** [comment] 2018-01-08 05:45
It's spigot fault, i checked it. 

When there is only one player online server will send full EntityMetaData packet on join - this will override all meta send by other server when switching (index 0) but when there is more players server will send only some data (i my case only index 13). Tested with clear server.

Some proof in logs: https://gist.github.com/Fejm/ecfa2c1d310b7a409d1dbcde2e0d890c

Code to generate log (needs ProtocolLib):  https://gist.github.com/Fejm/f92346c002c5230be729e9858b1a2e71

Correct me if i'm wrong.

**Comment by md-5** [comment] 2018-01-08 08:27
Thanks @Fejm , I wonder if you would be able to prepare a Spigot patch?
In any case closing as its not a bungee issue.

**Closed by md-5** 2018-01-08 08:27 UTC

**Comment by md-5** [comment] 2018-01-08 08:49
Looks like its because other clients get a first update, it marks it clean so that the player then won't get a complete update. Easiest fix is probably to just send the joining player a complete update straight off the bat.
