### ISSUE TITLE
/server <TAB> error

### ISSUE THREAD

**Issue by xtechgamer735** [SpigotMC/BungeeCord#2318] opened 2018-01-05 18:48 UTC
Hello All!

For some strange reason, when any player types /server and then presses TAB, they get disconnected and a stack trace like so appears:

https://gist.github.com/xtechgamer735/24e937ca7b1997516474a7e7a738b0b6

Don't suppose anyone knows how I could fix it?

**Comment by ninja-** [comment] 2018-01-05 18:52
Please try emptying the modules/ folder

**Comment by xtechgamer735** [comment] 2018-01-05 18:54
Thanks for your reply! No luck sadly :(

**Comment by ninja-** [comment] 2018-01-05 18:59
duplicate of https://github.com/SpigotMC/BungeeCord/issues/2233
looks like issue in one of your plugins - my guess would be that you accidently shaded bungeecord to your plugin jar ?

**Comment by xtechgamer735** [comment] 2018-01-05 19:08
Thanks, I will give this a try and check though the plugins first. AFAIK we haven't but anything is possible

**Comment by md-5** [comment] 2018-01-05 21:00
Try removing plugins and add them back slowly.

**Closed by md-5** 2018-01-05 21:00 UTC
