### ISSUE TITLE
[Ping Handler] -> <server name> - read timed out 

### ISSUE THREAD

**Issue by koca2000** [SpigotMC/BungeeCord#1959] opened 2016-09-29 20:29 UTC
I use [BungeeTabListPlus](https://www.spigotmc.org/threads/bungeetablistplus.10325/) on my BungeeCord server and I'm still getting this warning in console:
`[Ping Handler] -> <server name> - read timed out`
I already wrote to plugin developer and he said that it is not message from his plugin.

BungeeCord version: git:BungeeCord-Bootstrap:1.10-SNAPSHOT:0581e49:1190 
Server: Microsoft Windows Server 2008 R2

On server is running: IIS, Teamviewer, hMailServer, Filezilla, Cobian Backup, MS SQL, MySQL

BungeeCord config:

```
ip_forward: true
network_compression_threshold: 256
stats: ed4881a4-ad67-4ecf-b3ff-34a3b08e7db7
groups:
  koca2000:
  - admin
servers:
  studiodamage:
    address: localhost:25568
    restricted: false
    motd: '&9StudioDamage server(MC1.9.2)'
  hardcore:
    address: localhost:25563
    motd: '&Hardcore server(MC1.10)'
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- max_players: 20
  host: 0.0.0.0:25565
  bind_local_address: false
  ping_passthrough: true
  tab_list: GLOBAL_PING
  forced_hosts:
    hardcore.***********..cz: hardcore
    ***********.cz: studiodamage
  tab_size: 60
  force_default_server: false
  motd: '&9StudioDamage server'
  query_enabled: true
  query_port: 25565
  priorities:
  - studiodamage
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
```

**Comment by RoboMWM** [comment] 2016-09-29 20:30
and your bungee yaml/config?

**Comment by Phineas** [comment] 2016-09-29 20:35
@RoboMWM Confused to why you would need that...

**Comment by Phineas** [comment] 2016-09-29 20:37
Anyway, this issue is not necessarily to do with Bungee. "read time out" means Bungee lost connection to the "<servername>" for more than 5000ms (5s). Could you maybe show logs from the server with the issue?

**Comment by RoboMWM** [comment] 2016-09-29 20:38
Idk I'm not all too familiar with bungee but I assumed there was probably a configuration error with the server setup.

**Comment by koca2000** [comment] 2016-09-29 21:04
@Phineas There is no information, error or warning in server log and problem is on both servers. Also warning spam start when someone connect one of servers.

**Comment by Phineas** [comment] 2016-09-29 21:06
@koca2000 Could you give me the full proxy.log*?

**Comment by koca2000** [comment] 2016-09-29 21:13
```
23:09:37 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
23:09:37 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
23:09:37 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:0581e49:1190
23:09:38 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
23:09:38 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
23:09:38 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
23:09:38 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
23:09:38 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
23:09:38 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
23:09:38 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Loaded plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Loaded plugin SkinsRestorer version 11.0 by Th3Tr0LLeR
23:09:38 [INFO] Loaded plugin FastLogin version 1.8 by games647, http://github.com/games647/FastLogin/graphs/contributors
23:09:38 [INFO] Loaded plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Loaded plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Loaded plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Loaded plugin BungeeTabListPlus version 2.6.0 by CodeCrafter47
23:09:38 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Enabled plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] [SkinsRestorer] §2==============================================
23:09:38 [INFO] [SkinsRestorer] §e  SkinsRestorer Updater
23:09:38 [INFO] [SkinsRestorer] §e 
23:09:38 [INFO] [SkinsRestorer] §b    You are running v§a11.0
23:09:38 [INFO] [SkinsRestorer] §a    The latest version of SkinsRestorer!
23:09:38 [INFO] [SkinsRestorer] §e 
23:09:38 [INFO] [SkinsRestorer] §2==============================================
23:09:38 [INFO] Enabled plugin SkinsRestorer version 11.0 by Th3Tr0LLeR
23:09:38 [SEVERE] Z?? 29, 2016 11:09:38 ODP. com.zaxxer.hikari.HikariDataSource <init>
INFO: HikariPool-1 - Started.

23:09:38 [INFO] Enabled plugin FastLogin version 1.8 by games647, http://github.com/games647/FastLogin/graphs/contributors
23:09:38 [INFO] Enabled plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Enabled plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:38 [INFO] Enabled plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
23:09:39 [INFO] [BungeeTabListPlus] Starting UpdateChecker Task
23:09:39 [INFO] [BungeeTabListPlus] Loading default.yml
23:09:39 [INFO] [BungeeTabListPlus] A new version of BungeeTabListPlus (2.6.4) is available. Download from http://www.spigotmc.org/resources/bungeetablistplus.313/
23:09:39 [INFO] Enabled plugin BungeeTabListPlus version 2.6.0 by CodeCrafter47
23:09:39 [INFO] Listening on /0.0.0.0:25565
23:09:39 [INFO] Started query on /0.0.0.0:25565
23:09:45 [INFO] [/80.92.254.12:53156] <-> InitialHandler has connected
23:09:46 [INFO] [koca2000] <-> ServerConnector [studiodamage] has connected
23:09:47 [INFO] Netty is not using direct IO buffers.
23:10:20 [WARNING] [Ping Handler] -> hardcore - read timed out
23:10:20 [WARNING] [Ping Handler] -> studiodamage - read timed out
23:10:24 [WARNING] [Ping Handler] -> hardcore - read timed out
23:10:44 [WARNING] [Ping Handler] -> studiodamage - read timed out
23:10:48 [WARNING] [Ping Handler] -> hardcore - read timed out
23:10:48 [WARNING] [Ping Handler] -> studiodamage - read timed out
23:10:52 [WARNING] [Ping Handler] -> hardcore - read timed out
23:10:52 [WARNING] [Ping Handler] -> studiodamage - read timed out
23:10:56 [WARNING] [Ping Handler] -> hardcore - read timed out
23:10:56 [WARNING] [Ping Handler] -> studiodamage - read timed out
23:11:00 [WARNING] [Ping Handler] -> hardcore - read timed out
23:11:00 [WARNING] [Ping Handler] -> studiodamage - read timed out
23:11:04 [WARNING] [Ping Handler] -> hardcore - read timed out
23:11:04 [WARNING] [Ping Handler] -> studiodamage - read timed out

```

**Comment by Paulomart** [comment] 2016-09-29 22:20
Try running without plugins.

**Comment by koca2000** [comment] 2016-09-29 22:53
@Paulomart That won't solve the problem, because this warning only appear when I add server status to tablist.

**Comment by Janmm14** [comment] 2016-09-29 23:27
Looks like a plugin issue.

**Comment by Phineas** [comment] 2016-09-30 08:06
@koca2000 Does that plugin have a config where you specify server info to ping?

**Comment by CodeCrafter47** [comment] 2016-09-30 08:08
I don't think there is anything wrong with the way BungeeTabListPlus uses the BungeeCord API.

Basically it does call the [`ServerInfo#ping(net.md_5.bungee.api.Callback)`](http://ci.md-5.net/job/BungeeCord/ws/api/target/apidocs/net/md_5/bungee/api/config/ServerInfo.html#ping(net.md_5.bungee.api.Callback)) method for each server at a fixed interval.

**Comment by koca2000** [comment] 2016-09-30 15:43
Any ideas how to solve the problem?

**Comment by Janmm14** [comment] 2016-10-01 12:49
In that case I think the backend server which was tried to ping is offline / not reachable.

**Comment by koca2000** [comment] 2016-10-01 13:11
@Janmm14 I am connected to it.

**Comment by Proplex** [comment] 2016-10-04 09:25
What version of BTLP are you using? And what spigot build are the servers? I'm unable to reproduce this error.

**Comment by koca2000** [comment] 2016-10-04 17:28
@Proplex
BTLP: 2.6.4 (Lastest)
Spigot: git-Spigot-f6feaaa-f326992 (MC: 1.9.2)

**Comment by koca2000** [comment] 2016-10-14 13:46
Really? Nobody know how to solve the problem?

**Comment by koca2000** [comment] 2016-10-28 21:51
@md-5 Don't you know, how to solve the problem?

**Comment by i9hdkill** [comment] 2016-12-15 01:56
Not a bug, probably network issue or missconfiguration of a plugin.

**Closed by i9hdkill** 2016-12-15 01:56 UTC

**Comment by Foorack** [comment] 2018-02-01 18:11
@i9hdkill I suggest reopening this issue per the discussion in https://github.com/WaterfallMC/Waterfall/issues/197#issuecomment-362350728 and https://github.com/WaterfallMC/Waterfall/pull/200

**Comment by Foorack** [comment] 2018-03-30 13:38
@i9hdkill Any comment on this? As per my previous [comment](https://github.com/WaterfallMC/Waterfall/issues/197#issuecomment-357506626) we are still having a lot of spam because of this.

As noted in previous mentioned [comment WaterfallMC/Waterfall#197](https://github.com/WaterfallMC/Waterfall/issues/197#issuecomment-362350728).

> Using ServerInfo#ping with a server that is offline (not reachable, not 'offline-mode'), causes a WARNING message to be displayed noting a 'read time out' (through the generic HandlerBoss class)

I think it is wrong for the ServerInfo#ping to print an error message to console whenever there is a connection error. A more appropriate action in this case would be to throw an exception which the plugins could catch. And I want to stress this is not a bug introduced in Waterfall and is fully replicable if I switch to BungeeCord.

**Comment by i9hdkill** [comment] 2018-03-30 15:05
I will leave it to @md-5 to reopen it or not. But seems like this could be improved like you said.

**Comment by md-5** [comment] 2018-03-30 23:41
An exception is thrown, it's just also logged by bungee.
