### ISSUE TITLE
[Forge/Cauldron] Crash when switching servers with your cursor over a tile entity

### ISSUE THREAD

**Issue by Nentify** [SpigotMC/BungeeCord#1326] opened 2015-01-11 18:41 UTC
Hello,

I'm currently (and others) having an issue with moving between seperate Cauldron servers on a BungeeCord instance. @jk-5 recommended I open an issue here, so I'll explain it in as best detail as I can.

I'll use the issue I posted here (https://github.com/Nuchaz/BiblioCraft/issues/227) as an example.

If a user is on "server A" and there is a Bibliocraft table placed, the user will crash when switching to "server B". An example crash is shown here: http://hastebin.com/ufipugarab.coffee

Other findings (testing specifically with BiblioCraft table)
- The issue only occurs when the cursor/crosshair is directly over the table
- All servers have identical item/block IDs

Specifics:
- Bungee version: git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"54c9ade":1032
- Cauldron version: 1.1272.06.215
- Modpack/mods: www.technicpack.net/modpack/tekkify.2607/mods

People who may be interested/be able to give more info: @dualspiral @Hatventures (has the same issue) @jk-5 @Haidyn @the-ible

I will be troubleshooting further and I'll post any other findings. I figure it's worth posting here considering most mods have the issue.

Thanks!

**Comment by Nentify** [comment] 2015-01-11 18:58
With further testing:
- The crashes ONLY occur when your cursor is over a tile entity (vanilla or modded, tested with chests, BiblioCraft tables and MFR fertilisers, 100% success rate so far)
- The crash does not occur if you're looking at nothing or a 'block' (modded blocks such as ores are also fine)

* By looking at, your crosshair must be over the block

I haven't tested entities or items in users inventories, but I can say for sure that this occurs when your crosshair is over any type of tile entity.

**Comment by dualspiral** [comment] 2015-01-11 19:28
I've not got time to look at this in huge detail at the moment, but at first glance it does feel like this isn't necessarily a Bungee issue, more an artifact of the reset packet not really being expected by the mods in question. It might also be something that could be fixed by the Forge client, but I really can't speculate right now - I have little knowledge of the Forge platform as it currently stands and I've just gotten home after a long day travelling so my brain is mush!

**Comment by Nentify** [comment] 2015-01-11 20:19
Reproducing the issue is weird sometimes, I feel like it may depend on the number of users online or something. I can reproduce it 100% on the 2 main survival servers, but on the market server (like 5 people) the fertilizer won't cause a crash, but the table will, and on the dev server (just me), neither cause a crash. It's really weird, I don't know what to make of it, but it's definitely cursor + TEs and maybe some other sort of data.

**Comment by Nentify** [comment] 2015-01-11 22:08
http://pastebin.com/LUcmV6cB

I get this crash report when switching servers but just looking at regular blocks. I feel like some sort of data's being 'left behind' or something. I'm not entirely sure. Somehow invalid metadata is being sent here: https://github.com/Drayshak/EnderTech/blob/master/src/main/java/io/endertech/multiblock/block/BlockMultiblockGlass.java#L67

I don't know, I'm not entirely sure where the issue lies (with mods, Cauldron, Bungee or Forge), but finding the issue seems to be proving difficult. @bloodmc any ideas?

**Comment by dualspiral** [comment] 2015-01-11 22:35
I wonder if it's something to do with the timing between the reset packet being sent and the server switch occuring...

Consider this: once the reset packet is sent, the clinet returns to the frozen "vanilla Forge" state. Usually, the handshake would be quick enough for no more information to get through before the handshake completes and the server switch occurs.

What should happen is:

# Reset packet is sent
# Handshake completes with no other Forge packets coming through
# Server switches
# Disco

What might be happening is that during the handshake, other packets are getting through, but the mod in question has essentially been unloaded/client mapping changed - probably from the mod ID list being sent. In fact, that's probably it, once the mod list has been sent _and accepted_, packets from the old server are still getting through, but the new, potentially different IDs from the objects could be causing packets from the old server being translated incorrectly. 

We should stop all packets from the old server after the mod list has been exchanged and see if that works... once I get time to look at it.

**Comment by Nentify** [comment] 2015-01-11 22:38
That sounds quite realistic actually. Thanks for your help so far! I'll be around to try any dev builds.

**Comment by Nentify** [comment] 2015-01-12 20:22
Other crash reports when switching servers:

- http://pastebin.com/QBhaURNC
- http://pastebin.com/0j2SVg6g
- http://pastebin.com/5k91KsAd
- http://pastebin.com/6mB3dj3J (slightly odd one)

**Comment by Hatventures** [comment] 2015-01-13 12:36
From my experience, it was never about what you are looking at, but generally what is around you.
And the more mods you had loaded, the more chances you had to crash on server switch. (I suppose something isnt getting cleaned up at the right time).

As a result, and as a stop-gap solution we implemented the following:

On server change, cancel the switch, kick the player and set their reconnect server to the target player.
It isnt fancy, as the player is required to join back, but not too bad, as they just have to rejoin the same address.


Beside that, and even after the countless hours spent on the issue, i havent been able to figure out a proper solution. 
But maybe there's hope with this new issue opened :)

**Comment by dualspiral** [comment] 2015-01-13 18:24
Your crashes happen before the "dimension" switch occurs, right?

**Comment by Hatventures** [comment] 2015-01-13 18:25
@dualspiral Correct.

The game immediatly freezes, there's no dimension switch visible client-side, then ends up crashing.
When you see the dimension "screen" change, everything will be fine.

**Comment by dualspiral** [comment] 2015-01-13 18:49
Having a stab at fixing this at https://github.com/dualspiral/BungeeCord/tree/issue-1326.

First iteration - no idea if this will work or not. Thought just came to me. Have a go, see if it works or not. I expect it probably won't work perfectly, but with a bit of luck, it might do something right!

What it does is it moves the dimension switch to before the ID list is sent. All cancellable events have been called by then, and I don't think FML is likely kick by that point either.

Have a go. Fingers crossed.

https://dl.dropboxusercontent.com/u/28705212/BungeeCord.jar

**Comment by Nentify** [comment] 2015-01-13 18:51
Video showing crash: http://nentify.me/crash.mp4

**Comment by Hatventures** [comment] 2015-01-13 18:52
Will test it either today or tomorrow and will definitly get back to you.

Cheers @dualspiral

**Comment by dualspiral** [comment] 2015-01-13 18:53
Ta guys. As I say, no idea if it'll work, but fingers crossed!

**Comment by Nentify** [comment] 2015-01-13 18:56
No luck with last build, same crash w/ BiblioCraft tables.

**Comment by dualspiral** [comment] 2015-01-13 18:58
Ok, gutted. Will have a think about it.

**Comment by jk-5** [comment] 2015-01-13 19:00
This is an interesting problem. If we send the id update before the dimension switch, mods on server A may break. if we send the id update after the dimension switch, mods on server B may break. Maybe try sending dimension switch 1 first, then the id update and then dimension switch 2. Don't know if it will fix anything, but we can try

**Comment by dualspiral** [comment] 2015-01-13 19:12
@jk-5 It sure is. Might try the second dimension switch packet thing - what you say makes sense and it could work. Worth a shot.

I'm also wondering if just adding a delay of about half a second between the start of the dimension switch and sending the ID list might work - giving the client enough time to start the dimension switch - and thus make the workflow:

* Confirm mod list.
* Dimension switch start.
* Hold for a moment (not doing that yet)
* Send ID list - hoping that no more rendering will be done and the client has started the dimension switch
* Complete handshake as normal, and respawn.

What's interesting is that just about all errors here are cast errors on rendering - I wonder if we just need to give it enough time. Seems to me this could just be the good ol' fashioned race condition.

**Comment by jk-5** [comment] 2015-01-13 19:15
You do have a point there, but adding a delay feels really hacky to me. I think we are more likely to get race conditions with the delay than without, but it's worth a shot

**Comment by dualspiral** [comment] 2015-01-13 19:16
I agree - but at the moment, it's the best I've got. It might at least confirm the problem.

**Comment by dualspiral** [comment] 2015-01-13 19:20
Added a half second delay, updated the build. Hopeful, not expectant, see what happens...

**Comment by Nentify** [comment] 2015-01-13 19:36
Still crashed :(

**Comment by Nentify** [comment] 2015-01-17 01:05
Any extra thoughts on this?

**Comment by dualspiral** [comment] 2015-01-17 11:19
Not really. I still need to investigate whether it's to do with packets from the server, or if this is more of a client problem - just not had time. It's a tough one though, that's for sure.

**Comment by dualspiral** [comment] 2015-01-18 15:08
I've made a small tweak - I now disconnect from the previous server before the ID list is sent, but I haven't tested it yet. If the problem is indeed to do with server packets with old IDs being sent, then I hope this would resolve it - disconnecting from the server stops all packets from the old server. Looking through the code, I don't think this should cause any side-effects, at this point, no cancellation of server switched can occur by that point, and if the ID assignement fails, the client is likely to disconnect anyway.

I've not tested this as of yet, as I haven't got a setup that would actually reproduce this yet. I'll get around to that eventually. Fingers crossed!

https://dl.dropboxusercontent.com/u/28705212/BungeeCord.jar

**Comment by Nentify** [comment] 2015-01-18 15:17
Still crashing when tested with BiblioCraft table (client): http://pastebin.com/BUJ26qX8
Random location in world: http://pastebin.com/ZxZHw66H

**Comment by dualspiral** [comment] 2015-01-18 15:28
Thanks @Nentify - that takes out server packets from the equation. I think what must be going on, in this case, is that the client is refreshing itself on a tick, and the ID list has changed.

If I can call the dimention switch earlier - that is, as soon as the client accepts the mod list, _maybe_ it will mitigate this. What we really could do with is the client completely unloading the world (probably need to remove the inventory too, now I think about it) before we send the ID list down - which is what I was trying to accomplish by sending the dimension switch earlier. I can't send it that much earlier though - as an incorrect mod list would cause the connection to stop comtinuing, and the user would remain on the same server.

**Comment by Hatventures** [comment] 2015-01-18 15:34
@dualspiral While this sounds correct, i synced my ID lists between servers (same level.dat file, so same ID mapping), crashes still occurs.

**Comment by dualspiral** [comment] 2015-01-18 15:39
There is technically a point, however, where the ID lists have been reset during the handshake/server switch. I'd actually like to start the dimention switch _before_ we start the FML handshake - but we have to think about mod rejections.

I wonder if it is possible for me to start the dimension switch before we send the reset packet, and throw the user out if the mods don't work out. To be honest, actually, if mods get rejected, the handshake remains incomplete. So maybe we should just start the dimension switch super early...

Sorry if this looks like rambling, but it helps collect my thoughts...

**Comment by Hatventures** [comment] 2015-01-18 15:42
@dualspiral Dont ever be sorry when you're trying to actually help :)

Is it actually possible to set a player in "limbo" (as in, 2 dimensions) for a set amount of time?

**Comment by Nentify** [comment] 2015-01-18 15:44
I was thinking about that too as a temporary solution, or routing the player through a vanilla server. With IDs, is it possible during the handshake that the client generates its own ID list during the switch? That's all I can think of when some blocks change visually before the server switch. Although this may be irrelevant.

**Comment by dualspiral** [comment] 2015-01-18 15:47
@Hatventures From what I understand, more _between_ dimensions. You have to tell the client to start switching, and then where to respawn. At that point, the player is actually in neither.

@Nentify I think that's exactly what is going on - and the side effect would be what you are seeing - blocks changing visually. Routing through a vanilla server may not work - because there is still a reset. However, due to there being less to do, the chances of a crash will decrease.

**Comment by Hatventures** [comment] 2015-01-18 16:00
If i can remember correctly,
vanilla -> modded = OK
modded -> vanilla = CRASH

At least that's how it used to work prior 1.7. I honestly have not tried since then

**Comment by Nentify** [comment] 2015-01-18 16:11
I don't crash when moving from modded to vanilla with the BiblioCraft table crash (crashes 100% to any other Cauldron server)

**Comment by dualspiral** [comment] 2015-01-18 16:16
Updated the build again if you want to give that a go.

**Comment by Nentify** [comment] 2015-01-18 16:25
Same crashes

**Comment by dualspiral** [comment] 2015-01-18 16:27
:/

I'm stumped. I'll see if I can come up with a better idea - but I fear we may need to delve into the Forge Client...

**Comment by Nentify** [comment] 2015-01-18 16:33
I think @bloodmc is sort of familiar with the client, not sure how willing he'd be to help out though.

**Comment by Nentify** [comment] 2015-01-29 23:50
Could adding some debug to Cauldron/Bungee/client help find where the issue lies?

**Comment by AnodyneEntity** [comment] 2015-02-13 12:19
Not sure if this is reviving a dead topic or not, but I'll do some profiling with my servers, as this issue only happens for me when I'm around "Modded" blocks. but never while around vanilla blocks.

**Comment by dualspiral** [comment] 2015-02-13 12:34
It's not the servers that are the issue. It's the interplay between client and Bungee.

For the record, what I think is happening here is Bungee sends the reset packet at the beginning of a handshake. This resets Forge to the "Frozen" state - which I think means that all modded blocks are being cleared from the client's ID registry. This seems to not be so much of a problem, until the new ID list comes in. Blocks on the old server are now rendered as the new ID blocks. Best case scenario - blocks change for a moment before switching servers. Worst case, some entities are now blocks, or vice versa, and the client casts to completely the wrong thing.

We need to work out how to get Bungee to send the packets at a time that the old server is unloaded, or see if we can work with Forge to make this situation better on the client. I'm no expert on Forge - but as you can see, I've tried everything on the Bungee side with no success...

@Nentify - I guess logging messages during the handshake on the client side may help. I expect that the client crashes either when the Reset packet is sent, or when the new ID list is sent.

(Sorry I've not been in touch sooner, personal issues have recently been plauging me so I had to take a step back.)

**Comment by tf101-wizard** [comment] 2015-03-25 22:45
Any progress on solving this issue?

**Comment by tf101-wizard** [comment] 2015-04-19 06:09
This issue has been fixed for the most part the casting issue at least has been ive only been able to have crashes while switching servers once which was when i was looking at some underwater plants

```
java.lang.IllegalArgumentException: Unrecognized metadata
	at erogenousbeef.bigreactors.common.multiblock.block.BlockMultiblockGlass.func_149915_a(BlockMultiblockGlass.java:58)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.ChunkCache.func_147438_o(ChunkCache.java:97)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:163)
	at fastcraft.a.n.a(F:102)
	at fastcraft.Hooks.t(F:149)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

https://github.com/PunKeel/BungeeCord/commit/4989799002a5dc7c4215d983c7049665dc1e21af

**Comment by dualspiral** [comment] 2015-04-19 08:24
Yep - PR #1426 (mostly putting this here to link the issue and the PR together a little)

I'm not suprised it helps, because the problem has always been that moment between when the handshake is reset and the dimention switch occurs. The patch looks like it makes two dimention switches, one to reset entities, then the actual one. 

However, as you've seen, there is still a chance that things can fail. That's possibly due to one of two things:

* The mod still doesn't support this reset packet that Bungee sends
* There is still a moment where the game state on the client is reset back to vanilla, and the client hasn't started switching.

You see less of it because the server switch is faster. I still think there might need to be change to the Forge client to fix this completely.

**Comment by tf101-wizard** [comment] 2015-04-22 17:57
Well can you perform this fix to the forge client? PR it or something it's our #1 issue right now is players can't switch between instances without crashing

**Comment by tf101-wizard** [comment] 2015-04-23 05:25
After making a work around that teleports the user to a holding location before connecting to them to the new server it still crashes which is strange. I teleport them to a void world  which has nothing in it to crash them then connect them after a delay of 2 ticks. However this method did not work it still crashing on unrecognized metadata about BlockMultiblockGlass which is odd since there is nothing like that in the world to cause that.

Something is holding something it shouldn't

**Comment by AnodyneEntity** [comment] 2015-04-29 06:38
I'd like to know what changed in BungeeCord between 1.6.4 and 1.7.10, cause the crashes experienced now never use to be an issue in 1.6.4.

**Comment by Katelyn-SN** [comment] 2015-04-29 07:02
Already handled in our new plugin LoginHandler it uses holding locations with blocks that cast without crashing to mitigate these issues. The Bungee side has yet to be uploaded to github since it needs to be cleaned up but the bukkit version is there for you to browse through if you wish.

**Comment by dualspiral** [comment] 2015-04-29 08:24
@AnodyneEntity - it was FML that changed, not Bungee. Bungee needed to adapt to support it.

This really is a Forge/FML thing, the game state should only reset on dimension switch. I don't know FML enough to be able to fix this myself.

**Comment by i9hdkill** [comment] 2016-06-20 00:34
1.6/1.7 is no longer supported.
If anyone wishes to use 1.8.9 Sponge with BungeeCord IP-forwarding enabled, use the bungee plugin Spongepls.
https://forums.spongepowered.org/t/spongepls-bungeecord-forge-support/9891

**Closed by i9hdkill** 2016-06-20 00:34 UTC
