### ISSUE TITLE
Player get disconnect when joining

### ISSUE THREAD

**Issue by Zwoerni2000** [SpigotMC/BungeeCord#1900] opened 2016-06-28 16:02 UTC
Sometimes a player join a server, he get disconnected with "The server you were previously on went down, you habe been connected to the lobby."
Here is the log: http://hastebin.com/tiyadipipu.avrasm

**Comment by Janmm14** [comment] 2016-06-28 16:11
Are you using bungeecord plugins?
Do you use ip-forwarding?

**Comment by Zwoerni2000** [comment] 2016-06-28 16:13
IP-Forwarding enabled and no bungee plugins.

**Comment by i9hdkill** [comment] 2016-06-28 16:48
BungeeCord build? Looks like an outdated spigot plugin.

**Comment by WolverinDEV** [comment] 2016-06-28 17:29
Could can set the timeout higher then this may be fixed

**Comment by i9hdkill** [comment] 2016-07-04 07:41
No feedback since 6 days. Closing the ticket.
If you can reproduce this issue with a clean BungeeCord and clean spigot, give us a hint.

**Closed by i9hdkill** 2016-07-04 07:41 UTC
