### ISSUE TITLE
Missing show_entity enum constant

### ISSUE THREAD

**Issue by bibo38** [SpigotMC/BungeeCord#1708] opened 2016-01-16 18:01 UTC
Minecraft has introduced a HoverEvent with the action `show_entity`.
But this is currently not implemented in the [Chat API](https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/api/chat/HoverEvent.java), which causes a GSON error when trying to decode the JSON Raw message containing such a HoverEvent.

See: http://minecraft.gamepedia.com/Commands#Raw_JSON_text

**Comment by Black-Hole** [comment] 2016-01-16 18:14
There is a PR for this: https://github.com/SpigotMC/BungeeCord/pull/1324

**Comment by Black-Hole** [comment] 2016-01-16 18:17
This is also a duplicate of https://github.com/SpigotMC/BungeeCord/issues/1300

**Closed** 2016-01-16 23:57 UTC
