### ISSUE TITLE
BungeeCord not working with scoreboard

### ISSUE THREAD

**Issue by AcidSoap** [SpigotMC/BungeeCord#3559] opened 2023-11-05 10:13 UTC
### Bungeecord version

BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:f5157f1:1765

### Server version

git-Spigot-79a30d7-f4830a1 (MC: 1.12.2)

### Client version

1.12.2

### Bungeecord plugins

For me I have 2 servers
Bungee none
#1 authentication server
#2 Lobby server where player choose server
#1 server: AuthMe, ipwhitelist,LuckPerms,ProtocolLib
#2 Lobby: server  ipwhitelist TAB v 4.0.8

### The bug

Previously, to fix this, I downgraded BungeeCord to this https://ci.md-5.net/job/BungeeCord/1759/
For reproducing Im updated version BungeeCord to the last

I'l tried 4-5 scoreboards plugin, and none of them working

Steps for reproducing:
1. Start BungeeCord
2. Start server #1 authenticate
3. Connect and login auth server
4. Waiting for authme that send you to lobby server
5. AuthMe tried send you to Lobby But you see chat message
"The server you were previously on went down, you have been connected to the fallback server"
I checked logs in Lobby server but see only that i tried connect to the server and immediately left
Tried write help , server still alive.

### Log output (links)
Idk how to provide more detailed logs, if u explain me how get them i'll provide u them

[12:53:20] [Server thread/INFO]: Done (1,118s)! For help, type "help" or "?"
[12:54:58] [User Authenticator #1/INFO]: UUID of player steve
[12:54:58] [Server thread/INFO]: steve[/192.168.0.33:64193] logged in with entity id 1 at ([world]-15.201916190435924, 80.5, 215.03655804828827)
[12:55:09] [Server thread/INFO]: steve lost connection: Disconnected
[12:55:09] [Server thread/INFO]: steve left the game
[12:56:01] [Server thread/INFO]: Opped steve
[12:56:05] [User Authenticator #2/INFO]: UUID of player steve is fe7a0454-4012-3e27-b021-5004fef14d68
[12:56:05] [Server thread/INFO]: steve[/192.168.0.33:64206] logged in with entity id 2 at ([world]-15.201916190435924, 80.5, 215.03655804828827)
[12:56:05] [Server thread/INFO]: steve lost connection: Disconnected
[12:56:05] [Server thread/INFO]: steve left the game
[12:56:07] [User Authenticator #3/INFO]: UUID of player steve is fe7a0454-4012-3e27-b021-5004fef14d68
[12:56:07] [Server thread/INFO]: steve[/192.168.0.33:64208] logged in with entity id 3 at ([world]-15.201916190435924, 80.5, 215.03655804828827)
[12:56:07] [Server thread/INFO]: steve lost connection: Disconnected
[12:56:07] [Server thread/INFO]: steve left the game
[12:56:09] [User Authenticator #4/INFO]: UUID of player steve is fe7a0454-4012-3e27-b021-5004fef14d68
[12:56:09] [Server thread/INFO]: steve[/192.168.0.33:64210] logged in with entity id 4 at ([world]-15.201916190435924, 80.5, 215.03655804828827)
[12:56:09] [Server thread/INFO]: steve lost connection: Disconnected
[12:56:09] [Server thread/INFO]: steve left the game
[12:56:11] [User Authenticator #5/INFO]: UUID of player steve is fe7a0454-4012-3e27-b021-5004fef14d68
[12:56:11] [Server thread/INFO]: steve[/192.168.0.33:64212] logged in with entity id 5 at ([world]-15.201916190435924, 80.5, 215.03655804828827)
[12:56:11] [Server thread/INFO]: steve lost connection: Disconnected
[12:56:11] [Server thread/INFO]: steve left the game
[13:04:51] [User Authenticator #6/INFO]: UUID of player steve is fe7a0454-4012-3e27-b021-5004fef14d68
[13:04:51] [Server thread/INFO]: steve[/192.168.0.33:64260] logged in with entity id 6 at ([world]-15.201916190435924, 80.5, 215.03655804828827)
[13:04:51] [Server thread/INFO]: steve lost connection: Disconnected
[13:04:51] [Server thread/INFO]: steve left the game
[13:04:53] [User Authenticator #7/INFO]: UUID of player steve is fe7a0454-4012-3e27-b021-5004fef14d68
[13:04:53] [Server thread/INFO]: steve[/192.168.0.33:64262] logged in with entity id 7 at ([world]-15.201916190435924, 80.5, 215.03655804828827)
[13:04:53] [Server thread/INFO]: steve lost connection: Disconnected
[13:04:53] [Server thread/INFO]: steve left the game
[13:04:54] [User Authenticator #8/INFO]: UUID of player steve is fe7a0454-4012-3e27-b021-5004fef14d68
[13:04:54] [Server thread/INFO]: steve[/192.168.0.33:64264] logged in with entity id 8 at ([world]-15.201916190435924, 80.5, 215.03655804828827)
[13:04:54] [Server thread/INFO]: steve lost connection: Disconnected
[13:04:54] [Server thread/INFO]: steve left the game
[13:10:30] [Server thread/INFO]: [Server] Im still ALIVE!!!

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [ ] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment] 2023-11-05 10:36
Can you please give more minimal steps to reproduce?

I tried a vanilla scoreboard with no issues:

```
/scoreboard objectives add test dummy
/scoreboard objectives setdisplay sidebar test
/scoreboard players add @p test 1
```

**Comment by AcidSoap** [comment] 2023-11-05 10:44
Ok, then try another way. 
1. Broken yaml syntax tab config (While yaml broken error does not appear)
2. Connect in advance to server with TAB
3. Fix broken yaml syntax and /tab reload
Than BungeeCord send you to previous server and chat you error

**Comment by AcidSoap** [comment] 2023-11-05 10:52
I think you add scoreboard BEFORE player appear in server. When u trying add scoreboard while player on server i think error does not submitted

**Comment by AcidSoap** [comment] 2023-11-05 11:20
Oh, I got more detailed logs about error by enabling debug mode in spigot core. Are they contain some useful info about error?

[14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
[14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
[14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
[14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
[14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
[14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]

**Comment by Janmm14** [comment] 2023-11-05 12:17
> Oh, I got more detailed logs about error by enabling debug mode in spigot core. Are they contain some usefull info about error?
> 
> [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]

this does not contai nany useful information except that there is likely a plugin not correctly handling player disconnects.

**Comment by xism4** [comment] 2023-11-05 13:30
> > Oh, I got more detailed logs about error by enabling debug mode in spigot core. Are they contain some usefull info about error?
> > [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1] [14:15:21] [Netty Server IO #1/DEBUG]: Internal Exception: java.nio.channels.ClosedChannelException java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
> 
> This does not contain any useful information except that there is likely a plugin not correctly handling player disconnects. If you consult your log file from the top, the first errors related to ClosedchannelExceptions should be longer and have a "stack trace" (bunch of lines starting with "at"), these show which code tried to send data to a disconnected player.

Tab owner said on next version will be fixed

**Comment by andreasdc** [comment] 2023-11-06 05:46
> Can you please give more minimal steps to reproduce?
> 
> I tried a vanilla scoreboard with no issues, including server switching:
> 
> ```
> /scoreboard objectives add test dummy
> /scoreboard objectives setdisplay sidebar test
> /scoreboard players add @p test 1
> ```

Make objective with space in it

**Comment by md-5** [comment] 2023-11-06 09:08
> Make objective with space in it

How do I do that?

I see some issue with packet serialisation in old versions, but it wouldn't affect bungee itself, only a bungee plugin putting bungee-side scoreboards

**Closed** 2023-11-06 09:15 UTC

**Comment by andreasdc** [comment] 2023-11-06 16:34
> > Make objective with space in it
> 
> How do I do that?
> 
> I see some issue with packet serialisation in old versions, but it wouldn't affect bungee itself, only a bungee plugin putting bungee-side scoreboards

It was bukkit plugin in my situation, the problematic string was scoreboard name. Is the displayname as json for players/npcs fixed?

**Comment by md-5** [comment] 2023-11-06 19:29
If that came from score prefixes, yes. Glancing at the code I think the player list packet is ok

**Comment by andreasdc** [comment] 2023-11-06 19:40
> If that came from score prefixes, yes. Glancing at the code I think the player list packet is ok

It was the player name above head and on the tablist.

**Comment by md-5** [comment] 2023-11-06 19:44
> It was the player name above head and on the tablist.

Yes, but that can come from scoreboards.

If the issue is still present on 1767, please give step by step instructions to reproduce from a blank server

**Comment by andreasdc** [comment] 2023-11-08 18:06
> > It was the player name above head and on the tablist.
> 
> Yes, but that can come from scoreboards.
> 
> If the issue is still present on 1767, please give step by step instructions to reproduce from a blank server

Either is not needed here?
https://github.com/SpigotMC/BungeeCord/blob/bd8d114992a674ffb861182c44bc5a1a6b083752/protocol/src/main/java/net/md_5/bungee/protocol/packet/PlayerListItem.java#L82C49-L82C49

**Comment by md-5** [comment] 2023-11-08 19:24
No, that always seems to have been a component even in 1.8
