### ISSUE TITLE
Connections issue - bots attacks

### ISSUE THREAD

**Issue by lucas2107** [SpigotMC/BungeeCord#2532] opened 2018-09-28 05:41 UTC
Hi,

Since few months, bots attacks are more and more stronger, I'm a contributor of AntibotDeluxe plugin, and I recently noticed something unusual:

![screenshot_1](https://user-images.githubusercontent.com/11612016/46189976-cef6fc80-c2f1-11e8-9b74-96be6426c9cd.png)

When the attack start, number of connections are growing more and more, and when the limit is reached (Default 250k), the dedicated can't reach the network. Is Bungee closing connections correctly?

This attack was only 600-800 bots/s.
Some people can reach 2000/4000 bots/s.

Maybe the main developper of Antibotdeluxe did something wrong?

I noticed this only on Bungee (And forks of Bungee), this don't happend on Spigot.

Best regards,

**Comment by Leymooo** [comment] 2018-09-28 06:00
250k open connections? Are you really sure that it is a bot attack and not a L7 ddos atack with half open/closed connections?

**Comment by lucas2107** [comment] 2018-09-28 09:45
This is only bot attack. I tried myself.

**Comment by ninomato** [comment] 2018-10-02 15:38
Same problem with me, thanks for this statistics

**Comment by md-5** [comment] 2018-12-20 22:52
Closing as duplicate of #2535

**Closed by md-5** 2018-12-20 22:52 UTC
