### ISSUE TITLE
End command

### ISSUE THREAD

**Issue by CzlowiekKuktas** [SpigotMC/BungeeCord#1796] opened 2016-03-13 16:52 UTC
When you type /end test users are still disconnected with default message "Disconnected from the server".

**Comment by kamcio96** [comment] 2016-03-13 16:57
#1706 fix it

**Comment by CzlowiekKuktas** [comment] 2016-03-13 16:58
I have to fix this on my own?

**Comment by CzlowiekKuktas** [comment] 2016-03-13 18:45
@kamcio96 ?

**Comment by kamcio96** [comment] 2016-03-13 19:10
Hmm? I just send you link to my PR which fix it

**Comment by CzlowiekKuktas** [comment] 2016-03-13 19:10
So I have to edit it on my own, right?

**Comment by kamcio96** [comment] 2016-03-13 19:41
yes

**Comment by CzlowiekKuktas** [comment] 2016-03-13 19:42
I have problems with importing BungeeCord to Eclipse, can you help me?

**Comment by kamcio96** [comment] 2016-03-13 19:46
no

**Comment by CzlowiekKuktas** [comment] 2016-03-13 19:47
So how can I fix this?

**Comment by Janmm14** [comment] 2016-03-13 20:46
Use m2e maven to eclipse plugin.

**Comment by CzlowiekKuktas** [comment] 2016-03-24 22:37
@Janmm14 I don't know how.

**Comment by Janmm14** [comment] 2016-03-24 23:17
@CzlowiekKuktas I don't want to link lmgtfy. Its really easy. Install the plugin (if you don't have it) and say eclipse / the plugin that BungeeCord is a maven plugin.

Alternatively you can go for [Waterfall ](https://github.com/WaterfallMC/Waterfall) or [FlexPipe](https://github.com/minotopiame/FlexPipe), forks of bungeecord with various improvements. If you need Forge support, go for Waterfall, otherwise differences are low. They both provide downloads of .jar files.

**Comment by i9hdkill** [comment] 2016-06-26 14:40
Duplicate of #1387

**Closed by i9hdkill** 2016-06-26 14:40 UTC
