### ISSUE TITLE
Connection Issues kicking all players

### ISSUE THREAD

**Issue by MrFrostmaul** [SpigotMC/BungeeCord#1686] opened 2016-01-03 14:24 UTC
Hi,

We are currently having some issues with BungeeCord. It randomly started a few days ago after no configuration changes for the past 2 weeks and all of a sudden started and seen alot of posts on the forums, but no valid solution that works. Sometimes it is fine for an hour and then it will do constantly every few minutes and then continue on that sort of pattern.
I suspect it might be a connection issue between the servers, but all of our servers including the controller are running on the same dedicated machine.

Have seen: https://github.com/SpigotMC/BungeeCord/issues/303   about the connection throttle, but ours is already set to -1.

Error in Bungee Console: 
15:32:43 [WARNING] [PLAYER] <-> DownstreamBridge <-> [Hub] - read timed out
15:32:43 [INFO] [PLAYER] disconnected with: §fReadTimeoutException : null
15:32:43 [INFO] [PLAYER] disconnected with: §f[Proxy] Lost connection to server.
15:32:43 [INFO] [PLAYER] <-> DownstreamBridge <-> [Hub] has disconnected
15:32:43 [INFO] [PLAYER] -> UpstreamBridge has disconnected
15:32:47 [INFO] [/IP OF PLAYER:51299] <-> InitialHandler has connected

and also:
03.01 15:37:18 [Server] INFO disconnected with: [Proxy] Lost connection to server.
03.01 15:37:18 [Server] INFO -> UpstreamBridge has disconnected
 
While the player sees:  http://prntscr.com/9lljhl

Many Thanks with your help on this.

**Comment by MrFrostmaul** [comment] 2016-01-04 16:31
Anyone know a fix for this? yesterday it was fine without any issues and all of a sudden again today it's happening every few minutes.

**Comment by Janmm14** [comment] 2016-01-05 19:59
This looks like bungeecord freezes partly. This could be caused by a plugin, so a plugin list might help.

Do you get any bot attack or similar during the error?

**Comment by MrFrostmaul** [comment] 2016-01-06 00:25
I don't have any plugins installed on the Bungee Controller and only the Modules jars. I checked and there don't seem to be any attacks or high traffic etc.

**Comment by MrFrostmaul** [comment] 2016-01-08 19:08
I have moved the proxy onto it's own VPS and it seems to have resolved that issue....

But now when players are logged in, and on the lobby server or any other, if they want to go to another server it takes a good 10-15 second of nothing to send them there.

and also getting these errors as well.....

08.01 20:06:30 [Server] <-> DownstreamBridge <-> [Hub has disconnected
08.01 20:06:29 [Server] <-> ServerConnector [Survival has disconnected
08.01 20:06:29 [Server] <-> ServerConnector [Survival - read timed out
08.01 20:06:25 [Server] <-> DownstreamBridge <-> [Hub has disconnected
08.01 20:06:25 [Server] disconnected with: [Proxy Lost connection to server.
08.01 20:06:25 [Server] PLAYER -> UpstreamBridge has disconnected
08.01 20:06:25 [Server] PLAYER disconnected with: IOException : Connection reset by peer @ sun.nio.ch.FileDispatcherImpl:-2
08.01 20:06:25 [Server] PLAYER -> UpstreamBridge - IOException: Connection reset by peer

**Comment by MrFrostmaul** [comment] 2016-01-13 17:45
Issue seems to be resolved for me by updating to the latest version (one that came out 2 days ago at 10pm)

**Comment by Janmm14** [comment] 2016-03-02 20:22
@MrFrostmaul Consider closing if its solved.

**Closed** 2016-06-20 01:31 UTC
