### ISSUE TITLE
Bungeecord kicking players when accessing inventory in-game. DecoderException.

### ISSUE THREAD

**Issue by nikitis** [SpigotMC/BungeeCord#1729] opened 2016-01-31 17:00 UTC
When a user hits 'E' to access inventory, like clockwork gets kicked.  I tried with fresh config, with only ipforward=true set as I require it.  

Build 1109. CentOS7.  Using Java JCE cipher as it cannot load native library bungeecord-native-cipher from libcrypto.so

Error in bungeecord:
11:56:26 [INFO] Listening on /0.0.0.0:25565
11:56:28 [INFO] [nikitis] <-> InitialHandler has connected
11:56:31 [INFO] [nikitis] <-> ServerConnector [smp] has connected
11:56:44 [SEVERE] [nikitis] -> UpstreamBridge - encountered exception
io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException
    at io.netty.buffer.PooledHeapByteBuf.memoryAddress(PooledHeapByteBuf.java:262)
    at io.netty.buffer.SlicedByteBuf.memoryAddress(SlicedByteBuf.java:112)
    at net.md_5.bungee.jni.zlib.NativeZlib.process(NativeZlib.java:43)
    at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:42)
    at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:11)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    ... 19 more
11:56:44 [INFO] [nikitis] disconnected with: DecoderException : java.lang.UnsupportedOperationException @ io.netty.handler.codec.MessageToMessageDecoder:99
11:56:44 [INFO] [nikitis] -> UpstreamBridge has disconnected
11:56:44 [INFO] [nikitis] disconnected with: [Proxy] Lost connection to server.
11:56:44 [INFO] [nikitis] <-> DownstreamBridge <-> [smp] has disconnected

**Comment by nikitis** [comment] 2016-01-31 17:05
Did a clean setup, and past version check.  Issue is not present in 1105 and lower.  Started somewhere after 1105

**Comment by minecrafter** [comment] 2016-01-31 17:06
Duplicate of #1717

**Comment by nikitis** [comment] 2016-01-31 17:21
After reading #1717 a player stated with player skulls or player heads in inventory, it will cause something similar.  I reproduced and confirmed this is the case.  Without the playerhead in my inventory, the issue did NOT occur.    With the player head in my inventory, I was kicked immediately with the DecoderException error.

Confirmed.  Please merge with #1717

**Comment by md-5** [comment] 2016-01-31 23:53
https://github.com/SpigotMC/BungeeCord/issues/1717

**Closed by md-5** 2016-01-31 23:53 UTC
