### ISSUE TITLE
PingHandler 1.9 Gson Spam

### ISSUE THREAD

**Issue by Brian-Graham** [SpigotMC/BungeeCord#1765] opened 2016-03-01 00:23 UTC
https://paste.netcoding.net/eqewamutex.avrasm

	com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 17 path $.description

	Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 17 path $.description

	at net.md_5.bungee.connection.PingHandler.handle(PingHandler.java:57)
	at net.md_5.bungee.protocol.packet.StatusResponse.handle(StatusResponse.java:35)

Pinging servers (not sure if it's specific to Asynchronous pinging) results in an error.

**Comment by Digiw0lf** [comment] 2016-03-01 00:34
Having this same issue

**Comment by md-5** [comment] 2016-03-01 00:34
Can you be more specific. Is this with ping passthrough?

**Comment by Digiw0lf** [comment] 2016-03-01 00:36
Yes I have Ping Passthrough on

**Comment by Digiw0lf** [comment] 2016-03-01 00:37
Doesn't happen with Ping Passthrough disabled

**Comment by Brian-Graham** [comment] 2016-03-01 00:38
This happens to me with ping_passthrough disabled.

**Comment by md-5** [comment] 2016-03-01 00:38
Well I can't reproduce this, so I need more info.

**Comment by Brian-Graham** [comment] 2016-03-01 00:42
Here is our config.yml: https://paste.netcoding.net/ohajohugab.avrasm
The only plugin I have running is NiftyBungee: https://www.spigotmc.org/resources/niftybungee.564/

I run one ping every X milliseconds, which is somewhere between 100 and 600 (calculated). It fails 100% of the time on 1.9.

**Comment by md-5** [comment] 2016-03-01 00:43
So you're saying the error is with serverinfo.ping, not triggered by clients.

**Comment by Brian-Graham** [comment] 2016-03-01 00:43
Yes.

**Comment by Brian-Graham** [comment] 2016-03-01 00:48
Ok running **with no bungee plugins and the error eventually happens again**.

**Comment by minecrafter** [comment] 2016-03-01 01:25
The reason is simple. 1.9 uses text components by default instead of strings for the MOTD:
```
>>> slp.get_info("127.0.0.1")['description']
{u'text': u'A Minecraft Server'}
```

Fixing this should be simple by using `BaseComponent` in the description and custom serialization depending on the client version.

**Comment by minecrafter** [comment] 2016-03-01 01:29
I'll PR a fix for this

**Closed** 2016-03-01 01:38 UTC
Labels: Minecraft 1.9
